// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/commands/import": {
            "post": {
                "description": "Triggers the task import process from a specified directory",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "commands"
                ],
                "summary": "Import tasks from CSV",
                "responses": {
                    "200": {
                        "description": "Successful import response",
                        "schema": {
                            "$ref": "#/definitions/schemas.TaskImportResponse"
                        }
                    },
                    "500": {
                        "description": "Error import response",
                        "schema": {
                            "$ref": "#/definitions/schemas.TaskImportResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "schemas.TaskImportResponse": {
            "type": "object",
            "properties": {
                "errors": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "imported_at": {
                    "type": "string"
                },
                "message": {
                    "type": "string"
                },
                "stats": {
                    "$ref": "#/definitions/schemas.TaskImportStats"
                },
                "success": {
                    "type": "boolean"
                },
                "total_entries": {
                    "type": "integer"
                }
            }
        },
        "schemas.TaskImportStats": {
            "type": "object",
            "properties": {
                "duration_ms": {
                    "description": "Changed from time.Duration to int64",
                    "type": "integer"
                },
                "end_time": {
                    "type": "string"
                },
                "error_count": {
                    "type": "integer"
                },
                "start_time": {
                    "type": "string"
                },
                "success_count": {
                    "type": "integer"
                },
                "total_processed": {
                    "type": "integer"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "",
	Description:      "",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
