// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/auth/token": {
            "post": {
                "description": "Generates a JWT token for client authentication",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Generate JWT token",
                "parameters": [
                    {
                        "description": "Client credentials",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.GenerateTokenRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.GenerateTokenResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/dto.GenerateTokenResponse"
                        }
                    }
                }
            }
        },
        "/api/commands/import": {
            "post": {
                "description": "Triggers the task import process from a specified directory",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "commands"
                ],
                "summary": "Import tasks from CSV",
                "responses": {
                    "200": {
                        "description": "Successful import response",
                        "schema": {
                            "$ref": "#/definitions/schemas.TaskImportResponse"
                        }
                    },
                    "500": {
                        "description": "Error import response",
                        "schema": {
                            "$ref": "#/definitions/schemas.TaskImportResponse"
                        }
                    }
                }
            }
        },
        "/api/queries/tasks/active": {
            "get": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "description": "Retrieves all active tasks for a specific client",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "queries"
                ],
                "summary": "Get active tasks for a client",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/interfaces.TasksResponseDTO"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/interfaces.TasksResponseDTO"
                        }
                    }
                }
            }
        },
        "/api/queries/tasks/history": {
            "get": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "description": "Retrieves task status history for a client",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "queries"
                ],
                "summary": "Get task status history",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/interfaces.StatusHistoryResponseDTO"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/interfaces.StatusHistoryResponseDTO"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "dto.GenerateTokenRequest": {
            "type": "object",
            "required": [
                "client_id",
                "client_name"
            ],
            "properties": {
                "client_id": {
                    "description": "Client UUID for authentication",
                    "type": "string",
                    "example": "123e4567-e89b-12d3-a456-426614174000"
                },
                "client_name": {
                    "description": "Client name for authentication",
                    "type": "string",
                    "example": "Client One Corp"
                }
            }
        },
        "dto.GenerateTokenResponse": {
            "type": "object",
            "properties": {
                "message": {
                    "description": "Response message",
                    "type": "string",
                    "example": "Token generated successfully"
                },
                "success": {
                    "description": "Indicates if the operation was successful",
                    "type": "boolean",
                    "example": true
                },
                "token": {
                    "description": "JWT token if successful",
                    "type": "string",
                    "example": "eyJhbGciOiJIUzI1NiIs..."
                }
            }
        },
        "interfaces.StatusDetailDTO": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                },
                "status_description": {
                    "type": "string"
                },
                "task_id": {
                    "type": "integer"
                },
                "updated_by": {
                    "type": "string"
                }
            }
        },
        "interfaces.StatusHistoryResponseDTO": {
            "type": "object",
            "properties": {
                "history": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/interfaces.StatusDetailDTO"
                    }
                },
                "message": {
                    "type": "string"
                },
                "success": {
                    "type": "boolean"
                },
                "total_count": {
                    "type": "integer"
                }
            }
        },
        "interfaces.TaskDetailDTO": {
            "type": "object",
            "properties": {
                "client_id": {
                    "type": "string"
                },
                "client_name": {
                    "type": "string"
                },
                "department": {
                    "type": "string"
                },
                "email": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "is_active": {
                    "type": "boolean"
                },
                "name": {
                    "type": "string"
                },
                "position": {
                    "type": "string"
                }
            }
        },
        "interfaces.TasksResponseDTO": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string"
                },
                "success": {
                    "type": "boolean"
                },
                "tasks": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/interfaces.TaskDetailDTO"
                    }
                },
                "total_count": {
                    "type": "integer"
                }
            }
        },
        "schemas.TaskImportResponse": {
            "type": "object",
            "properties": {
                "errors": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "imported_at": {
                    "type": "string"
                },
                "message": {
                    "type": "string"
                },
                "stats": {
                    "$ref": "#/definitions/schemas.TaskImportStats"
                },
                "success": {
                    "type": "boolean"
                },
                "total_entries": {
                    "type": "integer"
                }
            }
        },
        "schemas.TaskImportStats": {
            "type": "object",
            "properties": {
                "duration_ms": {
                    "description": "Changed from time.Duration to int64",
                    "type": "integer"
                },
                "end_time": {
                    "type": "string"
                },
                "error_count": {
                    "type": "integer"
                },
                "start_time": {
                    "type": "string"
                },
                "success_count": {
                    "type": "integer"
                },
                "total_processed": {
                    "type": "integer"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "",
	Description:      "",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
